export const LOGIN = "user/signin"
export const SIGNUP = "user/signup"
export const ADD = "user/add"
export const TRANSFER = "user/transfer"
export const USER_BY_ID = "user/" 
export const GET_PROFILE = "user/get-profile" 